'use client';

import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Lang = 'en' | 'es';

// ─── Full translation dictionary ────────────────────────────────────────────
const DICT = {
  en: {
    // ── Brand ──
    brand_name: 'Belleza Reyna',
    brand_tagline: 'Inventory Suite',
    // ── Navigation ──
    nav_home: 'Home',
    nav_dashboard: 'Dashboard',
    nav_suppliers: 'Suppliers',
    nav_total_order: 'Total Order',
    nav_order_history: 'Order History',
    nav_behavior: 'Behavior',
    nav_description_home: 'Stock & behavior',
    nav_description_dashboard: 'KPIs & insights',
    nav_description_suppliers: 'Browse by supplier',
    nav_description_order: 'Products to order',
    nav_description_history: 'Confirmed orders',
    // ── Auth ──
    login_title: 'Welcome back',
    login_subtitle: 'Sign in to your Belleza Reyna account',
    login_email: 'Username',
    login_password: 'Password',
    login_button: 'Sign In',
    login_error: 'Invalid credentials. Please try again.',
    login_copyright: '© 2025 Belleza Reyna. All rights reserved.',
    logout: 'Sign Out',
    // ── Common ──
    search: 'Search…',
    all: 'All',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    save: 'Save',
    export: 'Export',
    import: 'Import',
    loading: 'Loading…',
    no_data: 'No data available',
    view_all: 'View all',
    back: 'Back',
    close: 'Close',
    select_all: 'Select all',
    deselect_all: 'Deselect all',
    selected: 'selected',
    skipped: 'skipped',
    // ── Inventory Hub ──
    hub_title: 'Inventory Hub',
    hub_last_import: 'Last import',
    hub_no_data: 'No data imported yet',
    hub_import_inventory: 'Import Inventory',
    hub_import_targets: 'Import Target Stock',
    hub_reset_data: 'Reset Data',
    hub_import_history: 'Import History',
    hub_product_behavior: 'Product Behavior',
    hub_current_inventory: 'Current Inventory',
    hub_full_analysis: 'Full Analysis',
    hub_in_stock: 'In Stock',
    hub_low: 'Low',
    hub_out: 'Out',
    hub_pending_targets: 'Pending Targets',
    hub_export_xlsx: 'Export .xlsx',
    hub_no_imports: 'No imports yet',
    hub_upload_first: 'Upload a CSV or Excel inventory file to get started',
    hub_import_first: 'Import first file',
    hub_need_2_snapshots: 'Import at least 2 snapshots to see product behavior trends.',
    hub_data_points: 'products with 2+ data points',
    // ── Dashboard ──
    dash_title: 'Dashboard',
    dash_kpi_inv_value: 'Inventory Value',
    dash_kpi_pending_order: 'Pending Order',
    dash_kpi_stock_alerts: 'Stock Alerts',
    dash_kpi_confirmed_orders: 'Confirmed Orders',
    dash_kpi_sfi: 'Stock Fulfillment',
    dash_kpi_oos: 'OOS Rate',
    dash_kpi_gap: 'Capital Gap',
    dash_kpi_overstock: 'Overstock',
    dash_stock_health: 'Stock Health Overview',
    dash_in_stock: 'In Stock (≥70% target)',
    dash_low_stock: 'Low Stock (20–70%)',
    dash_critical: 'Critical / Out (≤20%)',
    dash_top10: 'Top 10 Most Ordered',
    dash_by_supplier: 'Inventory Value by Supplier',
    dash_top_popular: 'Top Performing Products (by Daily Velocity)',
    dash_no_orders_yet: 'No confirmed orders yet.',
    dash_no_inventory: 'No inventory data yet.',
    dash_last_updated: 'Last updated',
    dash_tracking: 'Tracking',
    dash_of: 'of',
    dash_products: 'products',
    dash_items_to_order: 'items to order',
    dash_no_orders: 'No orders yet',
    dash_last: 'Last',
    dash_out_of: 'of',
    dash_at_zero: 'products at 0',
    dash_invest_sfi: 'Investment to reach 100% SFI',
    dash_click_overstock: 'Click to see ranked list →',
    dash_within_target: 'All products within target',
    // ── Orders ──
    orders_title: 'Total Order',
    orders_value: 'Order Value',
    orders_products: 'Products Selected',
    orders_units: 'Total Units',
    orders_confirm: 'Confirm Order',
    orders_priority: 'Priority Picks',
    orders_top_by_pop: 'Top by popularity',
    orders_rec_only: '— recommendation only, you decide',
    orders_ref: 'Ref',
    orders_description: 'Description',
    orders_supplier: 'Supplier',
    orders_current_stock: 'Current Stock',
    orders_units_to_order: 'Units to Order',
    orders_unit_cost: 'Unit Cost',
    orders_line_total: 'Line Total',
    orders_all_suppliers: 'All suppliers',
    orders_no_inventory: 'No inventory imported',
    orders_import_first: 'Import an inventory file first to see products that need ordering.',
    orders_go_home: 'Go to Home →',
    orders_all_ok: 'All stock levels are OK!',
    orders_no_products: 'No products need ordering right now.',
    orders_confirm_title: 'Confirm Order',
    orders_confirm_sub: 'This will move the order to history.',
    orders_products_to_order: 'Products to order',
    orders_total_units: 'Total units',
    orders_order_total: 'Order total',
    orders_confirm_note: 'Selected products will be confirmed and moved to Order History. Deselected products will remain in this list.',
    orders_confirming: 'Confirming…',
    orders_confirm_place: 'Confirm & Place Order',
    // ── History ──
    history_title: 'Order History',
    history_total_orders: 'Total Orders',
    history_total_value: 'Total Value',
    history_total_products: 'Products Ordered',
    history_top_product: 'Top Product',
    history_no_orders: 'No confirmed orders yet',
    history_place_first: 'Confirm your first order from the Total Order page.',
    history_go_orders: 'Go to Total Order →',
    history_order: 'Order',
    history_confirmed_at: 'Confirmed',
    history_items: 'items',
    history_stock_at_order: 'Stock at Order',
    history_units_ordered: 'Units Ordered',
    // ── Suppliers ──
    suppliers_title: 'Suppliers',
    suppliers_subtitle: 'Overview of your supplier network',
    suppliers_total_products: 'Total Products',
    suppliers_total_value: 'Total Value',
    suppliers_out_of_stock: 'OOS Products',
    suppliers_active: 'Active Suppliers',
    suppliers_search: 'Search supplier…',
    suppliers_no_data: 'No supplier data available.',
    suppliers_import_first: 'Import inventory to see supplier statistics.',
    suppliers_products: 'products',
    suppliers_oos: 'OOS',
    suppliers_low: 'Low',
    suppliers_view: 'View products →',
    suppliers_behavior: 'Supplier Behavior',
    suppliers_velocity: 'Avg velocity',
    // ── Product Behavior ──
    behavior_title: 'Product Behavior',
    behavior_snapshots: 'snapshots',
    behavior_products: 'products',
    behavior_import_new: 'Import New Snapshot',
    behavior_need_2: 'More data needed',
    behavior_need_2_msg: 'Import at least 2 snapshots to analyze product behavior.',
    behavior_quick_sale: 'Quick Sale',
    behavior_stable: 'Stable',
    behavior_slow_sale: 'Slow Sale',
    behavior_search: 'Search product…',
    behavior_popularity: 'Popularity Scores',
    behavior_product: 'Product',
    behavior_type: 'Type',
    behavior_score: 'Score',
    behavior_sales: 'Sales',
    behavior_select: 'Select a product to view details',
    behavior_total_sales: 'Total Sales',
    behavior_velocity: 'Velocity',
    behavior_consistency: 'Consistency',
    behavior_trend: 'Trend',
    behavior_rising: '↑ Rising',
    behavior_falling: '↓ Falling',
    behavior_stable_trend: '→ Stable',
    // ── Login ──
    ai_assistant: 'Reyna AI',
    ai_desc: 'AI assistant available on all pages. Set your Gemini API key to activate.',
    // ── Pending Approval ──
    pending_title: 'Access Pending Approval',
    pending_subtitle: 'Your account was created successfully. An admin must approve your access before you can use this app.',
    pending_signed_as: 'Signed in as',
    // ── Sign Up / Login extras ──
    signup_tab: 'Sign Up',
    signin_tab: 'Sign In',
    signup_email: 'Email',
    signup_full_name: 'Full Name',
    signup_confirm_pw: 'Confirm Password',
    signup_pw_mismatch: 'Passwords do not match.',
    signup_pw_short: 'Password must be at least 6 characters.',
    signup_success: 'Account created! An admin must approve your access before you can use the app. You will be notified once approved.',
    signup_team_note: 'All accounts share the same database — your team sees the same data.',
    signup_name_placeholder: 'Your name',
    signup_pw_placeholder: 'Min 6 characters',
    signup_pw_repeat: 'Repeat password',
    create_account: 'Create Account',
    enter: 'Sign In',
    // ── Inventory Hub extras ──
    inv_product: 'Product',
    inv_stock: 'Stock',
    inv_target: 'Target',
    inv_state: 'State',
    inv_search: 'Search by ref, name or supplier…',
    inv_files: 'files',
    inv_no_inventory: 'No inventory data',
    inv_import_snapshot_hint: 'Import a snapshot to see your current stock here',
    inv_no_match: 'No products match your search',
    // ── Import Modal ──
    import_supplier_name: 'Supplier Name',
    import_col_mapping: 'Column Mapping',
    import_not_mapped: '— Not mapped —',
    import_data_preview: 'Data Preview (first 5 rows)',
    import_products_ready: 'products ready to import',
    import_no_products_detected: 'No products detected — check your column mapping above',
    import_data_rows: 'data rows total',
  },
  es: {
    // ── Brand ──
    brand_name: 'Belleza Reyna',
    brand_tagline: 'Suite de Inventario',
    // ── Navigation ──
    nav_home: 'Inicio',
    nav_dashboard: 'Panel',
    nav_suppliers: 'Proveedores',
    nav_total_order: 'Pedido Total',
    nav_order_history: 'Historial de Pedidos',
    nav_behavior: 'Comportamiento',
    nav_description_home: 'Stock y comportamiento',
    nav_description_dashboard: 'KPIs e indicadores',
    nav_description_suppliers: 'Explora por proveedor',
    nav_description_order: 'Productos por pedir',
    nav_description_history: 'Pedidos confirmados',
    // ── Auth ──
    login_title: 'Bienvenida de nuevo',
    login_subtitle: 'Ingresa a tu cuenta de Belleza Reyna',
    login_email: 'Usuario',
    login_password: 'Contraseña',
    login_button: 'Iniciar sesión',
    login_error: 'Credenciales incorrectas. Por favor intenta de nuevo.',
    login_copyright: '© 2025 Belleza Reyna. Todos los derechos reservados.',
    logout: 'Cerrar sesión',
    // ── Common ──
    search: 'Buscar…',
    all: 'Todos',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    save: 'Guardar',
    export: 'Exportar',
    import: 'Importar',
    loading: 'Cargando…',
    no_data: 'Sin datos disponibles',
    view_all: 'Ver todo',
    back: 'Regresar',
    close: 'Cerrar',
    select_all: 'Seleccionar todo',
    deselect_all: 'Deseleccionar todo',
    selected: 'seleccionados',
    skipped: 'omitidos',
    // ── Inventory Hub ──
    hub_title: 'Centro de Inventario',
    hub_last_import: 'Última importación',
    hub_no_data: 'Aún no se han importado datos',
    hub_import_inventory: 'Importar Inventario',
    hub_import_targets: 'Importar Stock Objetivo',
    hub_reset_data: 'Reiniciar Datos',
    hub_import_history: 'Historial de Importaciones',
    hub_product_behavior: 'Comportamiento de Productos',
    hub_current_inventory: 'Inventario Actual',
    hub_full_analysis: 'Análisis Completo',
    hub_in_stock: 'En Stock',
    hub_low: 'Bajo',
    hub_out: 'Agotado',
    hub_pending_targets: 'Sin Objetivo',
    hub_export_xlsx: 'Exportar .xlsx',
    hub_no_imports: 'Aún no hay importaciones',
    hub_upload_first: 'Sube un archivo CSV o Excel de inventario para comenzar',
    hub_import_first: 'Importar primer archivo',
    hub_need_2_snapshots: 'Importa al menos 2 capturas para ver las tendencias de comportamiento.',
    hub_data_points: 'productos con 2+ puntos de datos',
    // ── Dashboard ──
    dash_title: 'Panel de Control',
    dash_kpi_inv_value: 'Valor del Inventario',
    dash_kpi_pending_order: 'Pedido Pendiente',
    dash_kpi_stock_alerts: 'Alertas de Stock',
    dash_kpi_confirmed_orders: 'Pedidos Confirmados',
    dash_kpi_sfi: 'Índice de Cumplimiento',
    dash_kpi_oos: 'Tasa de Agotados',
    dash_kpi_gap: 'Brecha de Capital',
    dash_kpi_overstock: 'Sobrestock',
    dash_stock_health: 'Resumen del Estado del Stock',
    dash_in_stock: 'En Stock (≥70% objetivo)',
    dash_low_stock: 'Stock Bajo (20–70%)',
    dash_critical: 'Crítico / Agotado (≤20%)',
    dash_top10: 'Top 10 Más Pedidos',
    dash_by_supplier: 'Valor de Inventario por Proveedor',
    dash_top_popular: 'Productos con Mayor Rendimiento (por Velocidad Diaria)',
    dash_no_orders_yet: 'Aún no hay pedidos confirmados.',
    dash_no_inventory: 'Aún no hay datos de inventario.',
    dash_last_updated: 'Última actualización',
    dash_tracking: 'Siguiendo',
    dash_of: 'de',
    dash_products: 'productos',
    dash_items_to_order: 'artículos por pedir',
    dash_no_orders: 'Sin pedidos aún',
    dash_last: 'Último',
    dash_out_of: 'de',
    dash_at_zero: 'productos en 0',
    dash_invest_sfi: 'Inversión para alcanzar 100% ICS',
    dash_click_overstock: 'Haz clic para ver la lista →',
    dash_within_target: 'Todos los productos dentro del objetivo',
    // ── Orders ──
    orders_title: 'Pedido Total',
    orders_value: 'Valor del Pedido',
    orders_products: 'Productos Seleccionados',
    orders_units: 'Unidades Totales',
    orders_confirm: 'Confirmar Pedido',
    orders_priority: 'Picks Prioritarios',
    orders_top_by_pop: 'Top por popularidad',
    orders_rec_only: '— solo recomendación, tú decides',
    orders_ref: 'Referencia',
    orders_description: 'Descripción',
    orders_supplier: 'Proveedor',
    orders_current_stock: 'Stock Actual',
    orders_units_to_order: 'Unidades a Pedir',
    orders_unit_cost: 'Costo Unitario',
    orders_line_total: 'Total de Línea',
    orders_all_suppliers: 'Todos los proveedores',
    orders_no_inventory: 'Sin inventario importado',
    orders_import_first: 'Importa un archivo de inventario primero para ver los productos que necesitan pedirse.',
    orders_go_home: 'Ir a Inicio →',
    orders_all_ok: '¡Todos los niveles de stock están bien!',
    orders_no_products: 'No hay productos que pedir en este momento.',
    orders_confirm_title: 'Confirmar Pedido',
    orders_confirm_sub: 'Esto moverá el pedido al historial.',
    orders_products_to_order: 'Productos a pedir',
    orders_total_units: 'Total de unidades',
    orders_order_total: 'Total del pedido',
    orders_confirm_note: 'Los productos seleccionados se confirmarán y se moverán al Historial de Pedidos. Los productos deseleccionados permanecerán en esta lista.',
    orders_confirming: 'Confirmando…',
    orders_confirm_place: 'Confirmar y Realizar Pedido',
    // ── History ──
    history_title: 'Historial de Pedidos',
    history_total_orders: 'Total de Pedidos',
    history_total_value: 'Valor Total',
    history_total_products: 'Productos Pedidos',
    history_top_product: 'Producto Principal',
    history_no_orders: 'Aún no hay pedidos confirmados',
    history_place_first: 'Confirma tu primer pedido desde la página de Pedido Total.',
    history_go_orders: 'Ir a Pedido Total →',
    history_order: 'Pedido',
    history_confirmed_at: 'Confirmado',
    history_items: 'artículos',
    history_stock_at_order: 'Stock al Pedir',
    history_units_ordered: 'Unidades Pedidas',
    // ── Suppliers ──
    suppliers_title: 'Proveedores',
    suppliers_subtitle: 'Resumen de tu red de proveedores',
    suppliers_total_products: 'Productos Totales',
    suppliers_total_value: 'Valor Total',
    suppliers_out_of_stock: 'Productos Agotados',
    suppliers_active: 'Proveedores Activos',
    suppliers_search: 'Buscar proveedor…',
    suppliers_no_data: 'No hay datos de proveedores disponibles.',
    suppliers_import_first: 'Importa inventario para ver estadísticas de proveedores.',
    suppliers_products: 'productos',
    suppliers_oos: 'Agotados',
    suppliers_low: 'Bajo',
    suppliers_view: 'Ver productos →',
    suppliers_behavior: 'Comportamiento del Proveedor',
    suppliers_velocity: 'Velocidad prom.',
    // ── Product Behavior ──
    behavior_title: 'Comportamiento de Productos',
    behavior_snapshots: 'capturas',
    behavior_products: 'productos',
    behavior_import_new: 'Importar Nueva Captura',
    behavior_need_2: 'Se necesitan más datos',
    behavior_need_2_msg: 'Importa al menos 2 capturas para analizar el comportamiento de los productos.',
    behavior_quick_sale: 'Venta Rápida',
    behavior_stable: 'Estable',
    behavior_slow_sale: 'Venta Lenta',
    behavior_search: 'Buscar producto…',
    behavior_popularity: 'Puntuaciones de Popularidad',
    behavior_product: 'Producto',
    behavior_type: 'Tipo',
    behavior_score: 'Puntaje',
    behavior_sales: 'Ventas',
    behavior_select: 'Selecciona un producto para ver detalles',
    behavior_total_sales: 'Ventas Totales',
    behavior_velocity: 'Velocidad',
    behavior_consistency: 'Consistencia',
    behavior_trend: 'Tendencia',
    behavior_rising: '↑ Subiendo',
    behavior_falling: '↓ Bajando',
    behavior_stable_trend: '→ Estable',
    // ── AI ──
    ai_assistant: 'Reyna IA',
    ai_desc: 'Asistente IA disponible en todas las páginas. Configura tu clave API de Gemini para activar.',
    // ── Pending Approval ──
    pending_title: 'Acceso Pendiente de Aprobación',
    pending_subtitle: 'Tu cuenta fue creada exitosamente. Un administrador debe aprobar tu acceso antes de que puedas usar esta aplicación.',
    pending_signed_as: 'Conectado como',
    // ── Sign Up / Login extras ──
    signup_tab: 'Crear Cuenta',
    signin_tab: 'Iniciar Sesión',
    signup_email: 'Correo electrónico',
    signup_full_name: 'Nombre completo',
    signup_confirm_pw: 'Confirmar contraseña',
    signup_pw_mismatch: 'Las contraseñas no coinciden.',
    signup_pw_short: 'La contraseña debe tener al menos 6 caracteres.',
    signup_success: '¡Cuenta creada! Un administrador debe aprobar tu acceso antes de usar la app. Serás notificado una vez aprobado.',
    signup_team_note: 'Al crear una cuenta, tu acceso es compartido con el equipo.',
    signup_name_placeholder: 'Tu nombre',
    signup_pw_placeholder: 'Mín. 6 caracteres',
    signup_pw_repeat: 'Repetir contraseña',
    create_account: 'Crear Cuenta',
    enter: 'Entrar',
    // ── Inventory Hub extras ──
    inv_product: 'Producto',
    inv_stock: 'Stock',
    inv_target: 'Objetivo',
    inv_state: 'Estado',
    inv_search: 'Buscar por referencia, nombre o proveedor…',
    inv_files: 'archivos',
    inv_no_inventory: 'Sin datos de inventario',
    inv_import_snapshot_hint: 'Importa una captura para ver tu stock actual aquí',
    inv_no_match: 'Ningún producto coincide con tu búsqueda',
    // ── Import Modal ──
    import_supplier_name: 'Nombre del Proveedor',
    import_col_mapping: 'Mapeo de Columnas',
    import_not_mapped: '— Sin mapear —',
    import_data_preview: 'Vista Previa (primeras 5 filas)',
    import_products_ready: 'productos listos para importar',
    import_no_products_detected: 'No se detectaron productos — verifica el mapeo de columnas',
    import_data_rows: 'filas de datos en total',
  },
} as const;

type TranslationKey = keyof typeof DICT['en'];

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    try {
      const stored = localStorage.getItem('reyna_lang') as Lang | null;
      if (stored === 'es' || stored === 'en') setLangState(stored);
    } catch {}
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try { localStorage.setItem('reyna_lang', l); } catch {}
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return (DICT[lang] as any)[key] ?? (DICT['en'] as any)[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
}
